export const USER_AUTH_VERIFY = 'USER_AUTH_VERIFY';
export const USER_AUTH_ERROR = 'USER_AUTH_ERROR';
export const NEED_VERIFY_EMAIL = 'NEED_VERIFY_EMAIL';
export const DID_SENT_EMAIL_VERIFICATION = 'DID_SENT_EMAIL_VERIFICATION';