export const USER_TOKEN_REQUEST = 'USER_TOKEN_REQUEST ';
export const USER_TOKEN_SUCCESS = 'USER_TOKEN_SUCCESS';
export const USER_TOKEN_ERRORS = 'USER_TOKEN_ERRORS';
export const USER_TOKEN_ERROR = 'USER_TOKEN_ERROR';
